### PR TITLE
feat: Show Work in Album Detail View

### PR DESCRIPTION
**Pull request by mayanez**
**Show Work in Album Detail View**

I have a large classical collection and thought this would be useful for others. It shows the `Work` tag in the album detail view to be able to more easily see the appropriate grouping much like it is done for `Disc`. This feature is toggle-able in much the same way as `Disc`.

Screenshot_20240718_131716

In the near future, I'd like to add the ability to queue up the tracks associated with a given work much the same way it is done for `Disc`.

Cheers!

### CODE REVIEW

**Comment by Emilot** [comment]
AWESOME! :)

**Comment by jcorporation** [comment]
Thanks for your contribution.

Code looks good. I think you forgot to print the value of the settings in the `mympd_api_settings_get` function. Please add this missing piece and rebase the pull request on the devel branch.

**Comment by mayanez** [comment]
> Code looks good. I think you forgot to print the value of the settings in the `mympd_api_settings_get` function. Please add this missing piece and rebase the pull request on the devel branch.

You're totally right! Addressed that and rebased against `devel`.

**Comment by jcorporation** [comment]
My fault, you must also create a merge request  into the devel branch and not the master branch. The master branch is always the latest stable release.

**Comment by mayanez** [comment]
My mistake. I forgot I needed to update the PR branch as well. Should be good now :smiley:

**Comment by jcorporation** [comment]
> In the near future, I'd like to add the ability to queue up the tracks associated with a given work much the same way it is done for Disc.

This feature is now added in the v18.0.0 branch.

**Pull request merged**
