### PR TITLE
Add Controls Attribute to Local Playback

### PR DESCRIPTION
**Pull request by 9ParsonsB**
It also adds a seek bar, which is ugly and not helpful for streaming, but at least I can adjust the volume

### CODE REVIEW

**Comment by jcorporation** [comment]
Volume should be also controllable through the JavaScript API. I think this is the better approach.

**Comment by 9ParsonsB** [comment]
How do I do that on a touch screen?

**Comment by jcorporation** [comment]
The volume change element must be manually added to the code.

**Comment by 9ParsonsB** [comment]
> Volume should be also controllable through the JavaScript API. I think this is the better approach.

I misunderstood this without your second comment. Apologies.

> The volume change element must be manually added to the code and JavaScript controls the volume.
> 
> I will add this for the 9.4.0 release.

Much thanks!

**Pull request closed without merging**
