### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by dream7180**
I have made translation for Chinese (Simplified), please consolidate it to the new version. Thank you.
The cn locale file will also be maintained in https://github.com/dream7180/mympd-chs-translation
[cn-CHS.txt](https://github.com/jcorporation/myMPD/files/8839220/cn-CHS.txt)

### CODE REVIEW

**Comment by jcorporation** [comment]
Great! But the pull request does not include the translation.

**Comment by dream7180** [comment]
> Great! But the pull request does not include the translation.
It does. May be the two links too closed.... 
https://github.com/jcorporation/myMPD/files/8839220/cn-CHS.txt

**Comment by jcorporation** [comment]
I close this pull request and merge the file manually into devel.

**Comment by jcorporation** [comment]
There are missing translations:
```
./build.sh translate 2>&1 | grep cn-CHS
Phrase "Alternative stream uri" for cn-CHS not found
Phrase "Alternative streams" for cn-CHS not found
Phrase "Bitrate" for cn-CHS not found
Phrase "Browser specific setting" for cn-CHS not found
Phrase "Click quick play button" for cn-CHS not found
Phrase "Cloud" for cn-CHS not found
Phrase "Codec" for cn-CHS not found
Phrase "Enforce mobile view" for cn-CHS not found
Phrase "Filenames" for cn-CHS not found
Phrase "Format" for cn-CHS not found
Phrase "Goto album" for cn-CHS not found
Phrase "Goto artist" for cn-CHS not found
Phrase "Listenbrainz Token" for cn-CHS not found
Phrase "MusicBrainz" for cn-CHS not found
Phrase "No outputs found" for cn-CHS not found
Phrase "Quick play" for cn-CHS not found
Phrase "Quick play button" for cn-CHS not found
Phrase "Quick remove button" for cn-CHS not found
Phrase "Show or hide" for cn-CHS not found
Phrase "Thumbnail names" for cn-CHS not found
Phrase "Thumbnail size" for cn-CHS not found
Phrase "kbit" for cn-CHS not found
```

**Comment by dream7180** [comment]
OK, I will check and update it soon.

**Pull request closed without merging**
