### PR TITLE
Fix Web Notifications in 8.1.x branch

### PR DESCRIPTION
**Pull request by Warr1024**
Fixes:

- Web notification checkbox not binding correctly (toggling whenever you hit Apply, not saving state)
- Web notifications never actually being sent
- Web notifications being displayed for Facilities that are disabled (no on-page notifications for them show)

### CODE REVIEW

**Review by jcorporation — CHANGES_REQUESTED** [review]
This bug is also in v8.2.0. I fixed it there with a different approach without duplicating code.

**Comment by Warr1024** [comment]
> This bug is also in v8.2.0. I fixed it there with a different approach without duplicating code.

I know.  I just wanted to make some fix available for the 8.1.x branch, since I can't get the 8.2 branch to work yet.

I figured this fix might warrant some refactoring, but when I went to do it, I don't understand the style or design well enough to know if exactly what the right fix is, e.g. are severity==='info' messages filtered out from on-page notifications entirely, and should that also apply to web notifications?  I was only able to get this as far as "working as far as I can tell for my use-cases" and if it needs something else for completeness/correctness then I'll need more guidance about specifically what.

I also assumed you're more focused on 8.2 development so fixes against 8.1 are just a stopgap until that's ready.

**Comment by jcorporation** [comment]
There are only some minor issues in your patch. Let me merge and fix it.

**Comment by jcorporation** [comment]
I merged this patch with some changes. Would you test?

**Comment by Warr1024** [comment]
Works fine to me.

**Pull request merged**
