### PR TITLE
Fix uninstalling/ purging

### PR DESCRIPTION
**Pull request by onkobu**
- removed repeated deletes of same directory/ file
- keep init-script upon uninstall
- remove init-script upon purge
- removed bogus variable from all rm paths

Signed-off-by: Onkobu Tanaake <onkobus-code@onkobutanaake.de>

### CODE REVIEW

**Comment by onkobu** [comment]
There is still inconsistent use of MYMPD_INSTALL_PREFIX, DESTDIR and hard coded paths I didn't fix. I'm uncertain about the intention of DESTDIR parallel to MYMPD_INSTALL_PREFIX. I assume MYMPD_INSTALL_PREFIX can be replaced by DESTDIR and the only hard coded /usr (builddebug) would turn into DESTDIR.

It cost me 13 seconds with my heart beating fast after the original uninstall removed my hand carved (Gentoo-) init script. And to restore it from my local repo.

**Comment by jcorporation** [comment]
The uninstall section is not as good it should be. Let us optimize this :)

1) Variables
DESTDIR is used by packaging scripts to install myMPD in a specific path.
MYMPD_INSTALL_PREFIX is used to determine the correct gnu install dirs.
That are two very different things.

2)
Which directories are deleted repeatedly? I see only /var/lib/mympd, right?

3)
Deleting the init script only in the purge section makes sense.

4)
Checking if the manifest is present has no advantage if the script tries anyway to delete the installation files by trial and error.

**Comment by onkobu** [comment]
My motivation is to lock mympd (or any other »experiment«) in /opt in its own subdirectory. So I can get rid of it by simple `rm -rf /opt/mympd`. (/usr is a separate partition/ device and for example AppArmor ensures that mympd is not reading outside /opt/mympd.)

Regarding 1.: So it was not correct to delete $DESTDIR from rm-invocations, since $DESTDIR could also be something like /tmp/v6.6.0? The intention wasn't obvious for me and also not explained sufficiently.

Regarding 2.: /var/lib/mympd was purged twice

Regarding 3.: uninstall must not delete files install didn't create. As far as I remember and with a short glimpse at the sources there is no init-script created/ installed. Nevertheless mympd.service is created during build.sh release and thus can be deleted or purged – it is your project, I can also amend my commit/ pull request and move mympd.service removal to purge. (A bit more background: depending on the distribution there is the one or the other nightmare. Normally init scripts are registered in a run level and this only works if the script exists. If it is removed it cannot be started and also cannot be removed from the runlevel easily. With busybox it is even more interesting having prefixed scripts with user chosen numbers to determine execution order, e.g. S60mympd to start after S10network and K61mympd to kill before K60apache.)

Regarding 4.: Depends on the previous not the current MYMPD_INSTALL_PREFIX in combination with DESTDIR.

I'd say it is easier to express such complex release scenarios as sort of profiles. Such a profile would be a collection of variables sourced into build.sh depending on some user input, e.g. `build.sh release -p pack-in-temp`. pack-in-temp would be a file next to build.sh containing adjustments for example DESTDIR. It'd also store this in release-directory as a sort of manifest.

**Comment by jcorporation** [comment]
To install myMPD under /opt/mympd you should use the MYMPD_INSTALL_PREFIX variable. (https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html)

The $DESTDIR variable is standard in packaging and should only used for this purpose. In other use cases $DESTDIR is empty. Therefore it would be good to keep it. (https://cmake.org/cmake/help/v3.12/envvar/DESTDIR.html)

> uninstall must not delete files install didn't create.

myMPD installs the systemd unit but also init scripts (cmake/CopyConfig.cmake).  Moving the removal process in the purge step is a good idea.

Using the install_manifest.txt is a good idea and should be the first choice. But what to do with files that are not listed there?
The /var/lib/mympd hierarchy is created on first startup, the configuration file is created with mympd-config in the install phase.

**Comment by jcorporation** [comment]
I have cherry-picked your 2 commits into my devel branch. I do not merge foreign branches in master, they must go through devel. Thanks for your contribution to myMPD.

**Pull request closed without merging**
