### PR TITLE
brotli compression support

### PR DESCRIPTION
**Pull request by dgcampea**
Most browsers support decompressing *brotli* content (https://caniuse.com/brotli).

## Size comparison
| File | gzip | brotli | difference |
|-----|--------|-------|----------------|
| htdocs/assets/MaterialIcons-Regular.woff2 | 161736 | 139978 | 21758 |
| htdocs/assets/coverimage-booklet.svg | 410 | 358 | 52 |
| htdocs/assets/coverimage-loading.svg | 413 | 353 | 60 |
| htdocs/assets/coverimage-mympd.svg | 293 | 249 | 44 |
| htdocs/assets/coverimage-notavailable.svg | 365 | 331 | 34 |
| htdocs/assets/coverimage-stream.svg | 419 | 369 | 50 |
| htdocs/assets/mympd-background-dark.svg | 269 | 246 | 23 |
| htdocs/assets/mympd-background-light.svg | 266 | 246 | 20 |
| htdocs/css/combined.css | 27211 | 20174 | 7037 |
| htdocs/js/combined.js | 121439 | 98991 | 22448 |
| htdocs/index.html | 15045 | 12373 | 2672 |
| htdocs/mympd.webmanifest | 305 | 250 | 55 |
| htdocs/sw.js | 671 | 540 | 131 |

### CODE REVIEW

**Comment by dgcampea** [comment]
It reduces the bandwidth usage and time to first byte (admittedly the savings are negligible unless it's being served a lot) though I'd argue the main benefit is from a distribution point of view (in the embedded assets case). It's specially relevant for the openwrt package, where we'd want to keep things as small as possible to preserve the flash memory endurance and space.

Overall the changes aren't too complex imo and it doesn't look like it would introduce any extra burden in maintaining it?

**Comment by jcorporation** [comment]
Release build with all features enabled decreases from 860k to 804k in size this is really noticeable. I merged it and kept it enabled by default. We can wait some time and the remove the gzip option if there are no problems with brotli.

**Comment by jcorporation** [comment]
Btw, there was a bug in your patch for the build script, fixed with https://github.com/jcorporation/myMPD/commit/562c7c8cf397b6c158512ef73d480eb40f0834c7

**Comment by GK-774** [comment]
Just tried it and with Firefox and Edge on Windows the decompression obviously fails and only a bunch of symbols is shown. On an iPad it works.

**Comment by GK-774** [comment]
Windows 10 Enterprise 21H2 OS build 19044.1645

Microsoft Edge
Version 101.0.1210.39 (Official build) (64-bit)

Firefox 100.0 (64-bit)

with brotli enabled ("Compressing assets with brotli" message) I get a page full of "�rFF!Y��`Y`3��" symbols on Firefox and a "ERR_CONTENT_DECODING_FAILED" on Edge. Rebuilt with brotli disabled it works as expected on both browsers.

What is the correct way to disable it? In my spec file I placed "export USE_BROTLI="OFF"" before the ./build.sh createassets command and used -DUSE_BROTLI=OFF for cmake, this worked but I´m courious what the "official" way would be.

**Comment by jcorporation** [comment]
> In my spec file I placed "export USE_BROTLI="OFF"" before the ./build.sh createassets command and used -DUSE_BROTLI=OFF for cmake, this worked but I´m courious what the "official" way would be.

That is correct, the `build.sh` script handles this the same way.

Your browser versions should definitively support brotli. Is there a proxy or anything else between myMPD and the browser?

**Comment by jcorporation** [comment]
We should track this within the new issue #753

**Pull request merged**
