### PR TITLE
Feat: Docker build

### PR DESCRIPTION
**Pull request by rollenwiese**
A working Docker container build.

I had to make a few minor changes to the mkrelease.sh script. The 'sudo' command isn't needed within the image build, so I made that aspect conditional, based on an environment variable set in the Dockerfile.

I may break out another feature branch and work on changing the configuration logic to read from an envronment variable as well as the configuration file, while giving precedence to environment variables. This would bring it in line with MPD, and allow the removal of the 'sed' commands from the contrib/docker/init.sh script.

### CODE REVIEW

**Comment by gerroon** [comment]
Is there a docker release somewhere? The original page does not exists

**Comment by jcorporation** [comment]
https://github.com/jcorporation/myMPD/packages

**Comment by gerroon** [comment]
Hi

So I tried this but getting

```
docker pull docker.pkg.github.com/jcorporation/mympd/mympd:6.2.3

Error response from daemon: Get https://docker.pkg.github.com/v2/jcorporation/mympd/mympd/manifests/6.2.3: no basic auth credentials
```


Also do you mind providing the basic flags for media volumes etc?

thanks

**Comment by jcorporation** [comment]
About docker pull:
https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/td-p/32782

I am no docker expert and can‘t provide docker related documentation. But if you figure it out, I add it gladly to the wiki.

**Pull request merged**
